export const GameConfig = {
  // Timing & Determinism
  FIXED_DELTA_TIME: 1 / 60,
  VIRTUAL_WIDTH: 1920,
  VIRTUAL_HEIGHT: 1080,

  // Background & Map Generation
  MAP_WIDTH: 2000,
  MAP_HEIGHT: 2000,
  HOUSE_COUNT: 8,
  BROKEN_HOUSE_COUNT: 10,
  TREE_COUNT: 150,
  RAVINE_COUNT: 12,
  DIRT_PATCH_COUNT: 30,

  // Player Config
  PLAYER_ACCEL_FACTOR: 15,
  PLAYER_DECEL_FACTOR: 10,
  PLAYER_MAX_HEALTH: 100,
  PLAYER_SPEED: 5,
  PLAYER_MASS: 500,
  PLAYER_DENSITY: 0.1,
  PLAYER_FRICTION_AIR: 0.05,
  PLAYER_BASE_DAMAGE: 20,
  PLAYER_ROTATION_SPEED: 0.05,
  PLAYER_TURRET_ROTATION_SPEED: 8.0,
  PLAYER_CHASSIS_ROTATION_SPEED: 10,
  PLAYER_ACCELERATION_TIME_SEC: 0.5,
  PLAYER_MAX_SPEED_MULTIPLIER: 2.0,
  PLAYER_RELOAD_TIME_MS: 500,
  PLAYER_BOOST_FORCE: 100,
  PLAYER_BOOST_COOLDOWN_SEC: 3.0,

  // Enemies
  ENEMY_BASE_HEALTH: 30,
  ENEMY_BASE_SPEED: 2.0, // lower speed
  ENEMY_SPEED_MULT_SHOOTER: 0.5,
  ENEMY_SPEED_MULT_RAMMER: 0.8,
  ENEMY_SPEED_MULT_KAMIKAZE: 1.5,
  ENEMY_SPAWN_INTERVAL_MS: 1000,
  ENEMY_SPAWN_MARGIN_PX: 100,
  ENEMY_XP_REWARD: 20,
  ENEMY_RAMMER_DAMAGE: 20,
  KAMIKAZE_EXPLOSION_RADIUS: 100,
  KAMIKAZE_DAMAGE: 40,
  KAMIKAZE_HEALTH: 20,
  AI_VIEW_RADIUS_PX: 500,
  AI_ALERT_RADIUS: 1000,
  AI_ATTACK_RADIUS: 600,
  AI_DESIRED_DIST: 350,
  AI_STRAFE_DIST: 500,
  AI_SEPARATION_RADIUS: 40,
  AI_OBSTACLE_AVOID_RADIUS: 150,
  AI_OBSTACLE_PADDING_PX: 40,
  AI_WALL_AVOIDANCE_RADIUS: 50,
  AI_DEFAULT_AVOIDANCE_RADIUS: 20,
  AI_SPATIAL_GRID_ENEMY_CELL: 100,
  AI_SPATIAL_GRID_OBSTACLE_CELL: 200,
  AI_PATH_RECALC_INTERVAL_FRAMES: 30,
  AI_STEERING_WEIGHTS: {
    seek: 1.0,
    separation: 1.5,
    avoidObstacles: 2.0,
  },

  // Physics
  PHYSICS_TIME_SCALE: 1.0,
  PHYSICS_GRAVITY: { x: 0, y: 0 }, // Top-down, gravity = 0
  PHYSICS_LATERAL_DAMPING: 0.2, // 80% dampen lateral vel
  PHYSICS_FORCE_MULT: 0.005,

  // Spawn
  SPAWN_MARGIN: 50,
  DIFFICULTY_RAMP_PER_MINUTE: 0.1,
  TICK_RATE: 60,

  // Visual Effects
  DAMAGE_FLASH_FRAMES: 8,
  DAMAGE_FLASH_TINT: 0xff8888,
  GOLD_RUSH_TINT: 0xffd700,
  INVULNERABILITY_TINT: 0x88bbff,
  INVULNERABILITY_BLINK_CYCLE_FRAMES: 8,
  INVULNERABILITY_BLINK_HALF_CYCLE_FRAMES: 4,
  INVULNERABILITY_ALPHA_MIN: 0.3,
  INVULNERABILITY_ALPHA_MAX: 0.8,
  DEFAULT_TINT: 0xffffff,
  DEFAULT_SPRITE_ALPHA: 1.0,
  WRECK_TINT: 0x666666,

  // Combat Timing
  INVULNERABILITY_FRAMES: 12,
  KILL_STREAK_DECAY_TIME: 3.0,
  EVASION_SLOWMO_DURATION: 0.2,
  EVASION_SLOWMO_SCALE: 0.3,

  // Combat
  PROJECTILE_SPEED_PLAYER: 15,
  PROJECTILE_SPEED_ENEMY: 4,
  PROJECTILE_DAMAGE_ENEMY: 10,
  PROJECTILE_LIFETIME_SEC: 2.0,

  // Upgrades
  UPGRADE_EXPLOSIVE_RADIUS: 60,
  AUTO_GUN_COOLDOWN_MS: 300,
  AUTO_GUN_DAMAGE: 5,
  AUTO_GUN_RANGE_PX: 200,
  CLUSTER_SPREAD_ANGLE: 0.15,

  // Synergies
  SYNERGY_ADRENALINE_DURATION_SEC: 1.5,
  SYNERGY_ADRENALINE_SPEED_MULT: 1.4,
  SYNERGY_ADRENALINE_MAX_TIMER_FRAMES: 90,
  SYNERGY_SHRAPNEL_RADIUS_MULT: 0.5,
  SYNERGY_REACTIVE_ARMOR_DEFLECTIONS_NEEDED: 4,
  SYNERGY_REACTIVE_ARMOR_HEAL: 15,
  SYNERGY_AUTO_VOLLEY_COOLDOWN_MULT: 1.15,
  SYNERGY_AUTO_VOLLEY_SHOTS: 2,
  SYNERGY_VAMPIRIC_ARMOR_HEAL: 10,
  SYNERGY_NAPALM_MINIGUN_COOLDOWN_MULT: 0.5,

  // Render
  TILE_SIZE_PX: 32,
  CAMERA_LERP_FACTOR: 0.1,
  BOILING_LINE_JITTER_PX: 1,
  BOILING_LINES_INTERVAL_FRAMES: 8,

  // Particles
  PARTICLE_SPAWN_CHANCE_MOVING: 0.03,
  PARTICLE_SPAWN_CHANCE_KAMIKAZE: 0.06,
  PARTICLE_OFFSET_RADIUS: 25,
  PARTICLE_CLOUD_BASE_LIFETIME: 1.0,
  PARTICLE_CLOUD_START_SCALE_MIN: 0.4,
  PARTICLE_CLOUD_START_SCALE_MAX: 1.0,
  PARTICLE_CLOUD_END_SCALE: 0.0,
  MUZZLE_FLASH_LIFETIME: 0.1,
  MUZZLE_FLASH_START_SCALE: 1.0,
  MUZZLE_FLASH_END_SCALE: 1.5,
  MUZZLE_FLASH_START_ALPHA: 1.0,
  MUZZLE_FLASH_END_ALPHA: 0.0,
  MUZZLE_FLASH_LENGTH: 35,
  MUZZLE_FLASH_WIDTH: 20,
  
  SMOKE_CLOUD_BASE_LIFETIME: 4.0,
  SMOKE_CLOUD_LIFETIME_VAR: 2.0,
  SMOKE_CLOUD_START_SCALE: 1.5,
  SMOKE_CLOUD_END_SCALE: 2.5,
  SMOKE_CLOUD_START_ALPHA: 0.8,
  TRACK_MARK_START_ALPHA: 0.3,
  TRACK_MARK_END_ALPHA: 0.0,

  // UI
  UI_INPUT_LOCK_MS: 500,
  UI_ANIMATION_DURATION_MS: 400,
} as const;
