export const en = {
    tankGame: "TANK GAME",
    play: "Play",
    goldRush: "GOLD RUSH!",
    health: "Health",
    level: "LVL",
    exp: "EXP",
    speed: "SPEED",
    fps: "FPS",
    levelUp: "Level Up!",
    wasted: "Wasted",
    wastedDescription: "Your tank has been destroyed.",
    tryAgain: "Try Again",
    bang: "BANG!",
    pow: "POW!",
    bam: "BAM!",
    crash: "CRASH!",
    boom: "BOOM!",
    killingSpree: "KILLING\nSPREE",
    rampage: "RAMPAGE!",
    unstoppable: "UNSTOPPABLE!",
    godlike: "GODLIKE!",
    goldRushLong: "GOLD\nRUSH!",
    whoosh: "WHOOSH!",
    upgrades: {
        health: { name: "Repair Kit", description: "+20 Max HP & Heal 50 HP" },
        speed: { name: "Engine Tuning", description: "+0.5 Movement Speed" },
        damage: { name: "Heavy Shells", description: "+10 Damage" },
        armor: { name: "Sloped Armor", description: "+15% Ricochet Chance" },
        autogun: { name: "Machine Gun", description: "Auto-fires at nearby enemies" },
        explosive: { name: "Explosive Ammo", description: "Area damage on impact" },
        multishot: { name: "Cluster Gun", description: "Fires 2 extra projectiles" },
        fireRate: { name: "Autoloader", description: "+20% Fire Rate" },
        vampirism: { name: "Vampiric Coating", description: "10% chance to heal on hit" },
        piercing: { name: "Armor Piercing", description: "Projectiles pierce 1 enemy" },
        agility: { name: "Agility Training", description: "10% Evasion chance" },
        critical: { name: "Weakpoint Targeting", description: "+15% Crit chance" },
    }
};

export type Localization = typeof en;
