export const en = {
    tankGame: "TANK GAME",
    play: "Play",
    goldRush: "GOLD RUSH!",
    health: "Health",
    level: "LVL",
    exp: "EXP",
    speed: "SPEED",
    fps: "FPS",
    wave: "WAVE",
    tier: "TIER",
    score: "SCORE",
    time: "TIME",
    tierUp: "TIER UP!",
    waveStart: "WAVE {wave}!",
    waveComplete: "WAVE COMPLETE!",
    levelUp: "Level Up!",
    wasted: "Wasted",
    wastedDescription: "Your tank has been destroyed.",
    tryAgain: "Try Again",
    bang: "BANG!",
    pow: "POW!",
    bam: "BAM!",
    crash: "CRASH!",
    boom: "BOOM!",
    killingSpree: "KILLING\nSPREE",
    rampage: "RAMPAGE!",
    unstoppable: "UNSTOPPABLE!",
    godlike: "GODLIKE!",
    goldRushLong: "GOLD\nRUSH!",
    whoosh: "WHOOSH!",
    upgrades: {
        health: { name: "Repair Kit", description: "+20 Max HP & Heal 50 HP" },
        speed: { name: "Engine Tuning", description: "+0.5 Movement Speed" },
        damage: { name: "Heavy Shells", description: "+10 Damage" },
        armor: { name: "Sloped Armor", description: "+15% Ricochet Chance" },
        autogun: { name: "Machine Gun", description: "Auto-fires at nearby enemies" },
        explosive: { name: "Explosive Ammo", description: "Area damage on impact" },
        multishot: { name: "Cluster Gun", description: "Fires 2 extra projectiles" },
        fireRate: { name: "Autoloader", description: "+20% Fire Rate" },
        vampirism: { name: "Vampiric Coating", description: "10% chance to heal on hit" },
        piercing: { name: "Armor Piercing", description: "Projectiles pierce 1 enemy" },
        agility: { name: "Agility Training", description: "10% Evasion chance" },
        critical: { name: "Weakpoint Targeting", description: "+15% Crit chance" },
        napalmMinigun: { name: "Napalm Minigun", description: "SYNERGY: Machine Gun + Explosive Ammo. Exploding auto-fire!" },
        vampiricArmor: { name: "Vampiric Armor", description: "SYNERGY: Vampiric Coating + Sloped Armor. Deflections heal you!" },
        ricochet: { name: "Ricochet", description: "SYNERGY. Bounces to nearest enemy after pierce." },
        adrenaline: { name: "Adrenaline", description: "SYNERGY. Kill gives +40% speed for 1.5s." },
        shrapnel: { name: "Shrapnel", description: "SYNERGY. Crits create mini-explosions." },
        overload: { name: "Overload", description: "SYNERGY. +30% Fire Rate, -10% Damage." },
        reactiveArmor: { name: "Reactive Armor", description: "SYNERGY. Every 4th deflection heals 15 HP." },
        predator: { name: "Predator", description: "SYNERGY. Next shot after evasion is 100% crit." },
        autoVolley: { name: "Auto-Volley", description: "SYNERGY. Autogun fires 2 shots but has +15% cooldown." },
        chains: { name: "Chains", description: "Projectiles chain to nearby enemies" },
        caliber: { name: "Large Caliber", description: "+25% Projectile Size" },
        repulsor: { name: "Repulsor", description: "Projectiles knock back enemies" },
        seismic: { name: "Seismic", description: "SYNERGY. Explosions knock back enemies in radius." },
        stasis: { name: "Stasis", description: "SYNERGY. Knocked back enemies are slowed for 0.5s." }
    }
};

export type Localization = typeof en;
